### ISSUE TITLE
Build failure in serialiser.h

### ISSUE THREAD

**Issue by bentley** [apertium/apertium#15]
Apertium (3.5.0 and master) fails to build on OpenBSD -current with clang-6.0.0.

    libtool: compile:  c++ -DHAVE_CONFIG_H -I. -I.. -I/usr/local/include/lttoolbox-3.4 -I/usr/local/lib/lttoolbox-3.4/include -I/usr/local/include/libxml2 -I/usr/local/include -I/usr/local/include -I/usr/local/include/lttoolbox-3.4 -I/usr/local/lib/lttoolbox-3.4/include -I/usr/local/include/libxml2 -I/usr/local/include -Wall -Wextra -g -O2 -std=c++2a -MT collection.lo -MD -MP -MF .deps/collection.Tpo -c collection.cc  -fPIC -DPIC -o .libs/collection.o
    In file included from collection.cc:20:
    In file included from ../apertium/serialiser.h:28:
    /usr/local/include/lttoolbox-3.4/lttoolbox/serialiser.h:239:34: error: member
          reference base type 'const unsigned long' is not a structure or union
      uint64_t size = SerialisedType_.size();
                      ~~~~~~~~~~~~~~~^~~~~
    collection.cc:96:23: note: in instantiation of member function '(anonymous
          namespace)::Serialiser<unsigned long>::serialise' requested here
      Serialiser<size_t>::serialise(element.size(), serialised);
                          ^
    In file included from collection.cc:20:
    In file included from ../apertium/serialiser.h:28:
    /usr/local/include/lttoolbox-3.4/lttoolbox/serialiser.h:242:17: error: type
          'unsigned long' cannot be used prior to '::' because it has no members
      for (typename Container::const_iterator value_type_ =
                    ^
    In file included from collection.cc:21:
    In file included from ../apertium/deserialiser.h:28:
    /usr/local/include/lttoolbox-3.4/lttoolbox/deserialiser.h:212:53: error: member
          reference base type 'typename std::remove_const<unsigned long>::type'
          (aka 'unsigned long') is not a structure or union
          std::inserter(SerialisedType_, SerialisedType_.begin());
                                         ~~~~~~~~~~~~~~~^~~~~~
    collection.cc:105:39: note: in instantiation of member function
          'Deserialiser<unsigned long>::deserialise' requested here
      size_t size = Deserialiser<size_t>::deserialise(serialised);
                                          ^
    3 errors generated.

**Comment by TinoDidriksen** [comment]
Actually an lttoolbox issue from this commit: https://github.com/apertium/lttoolbox/commit/fb61b829bab0565487320854d0c1c66fc2274071
